apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llmfirewall.fullname" . }}
  labels: {{- include "llmfirewall.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "llmfirewall.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "llmfirewall.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: LLMFW_CHROMADB_PERSIST_DIRECTORY
              value: /data/chromadb
            - name: LLMFW_MODEL_CACHE_DIR
              value: /data/models
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: "{{ $val }}"
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 120
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources: {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "llmfirewall.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
