{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "llmfirewall.fullname" . }}
  labels: {{- include "llmfirewall.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "llmfirewall.name" . }}
  endpoints:
    - port: http
      interval: {{ .Values.serviceMonitor.interval }}
      path: /metrics
{{- end }}
